### ISSUE TITLE
Thesaurus support

### ISSUE THREAD

**Issue by ByronCinNZ** [OpenWork-NZ/mdwg#100]
The thesaurus support system is a valuable way to capture keywords. But it has a number of issues:
- Seems not to have been migrated to 19115-3 and still uses 19139 schemas. Several sub-issues are likely the result of this 
- The SKOS schema to which a thesaurus must adhere is not documented anywhere I can find
- Keyword Class does not seem to travel with the thesaurus entry. This is likely due to thesaurus support not being udated from 139 to 115-3
- records populated through a thesaurus are not labeled as keywords in the interface. General look and feel improvements could be made to sections popupated this way.
- Keyword typecode is not complete to 19115-3. Likely due to nonmigration to 19115-3
- loading thesaurus is problematic and often partial with little indication of what went wrong or how to fix.
- compute extents from placename keywords are not functioning. Could be related to mismatch 139 and 115-3?
![image](https://user-images.githubusercontent.com/1085756/94624448-fafb4d00-0312-11eb-9d68-10404c951ef8.png)

**Comment by alcinnz** [comment]
Moved to relevant fork.
