### ISSUE TITLE
Metadata identifier

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#33]
Difficult to figure out how to setup a custom URN. They do have instructions https://geonetwork-opensource.org/manuals/turnk/administrator-guide/managing-metadata-standards/metadata-identifier.html The functionality also appears to be broken. URN templates seem not to be working.

Weakness: It doesn't allow us to automatically create an authority for the metadata.

We're still getting a GN-generated UUID instead of a custom one.

The codespace has an unchangable value of urn:uuid.

As per conversation with Francois Prunya the recommendation of using the codespace to hold the root namespace cannot be done.
Shortterm actions: use MetadataLinkage to hold the resolvable URI UUID.

Make sure when harvested by Dublin Core & similar catalogues that this maps to ID.
Medium term: See if you can fix the custom UUID.
Long term: Resolve larger issues around UUID assignment & relationship to URL. Needs to be easy for the user.

Template needs more automation for custom UUIDs. e.g. attach autogenerated UUID to custom namespace.
Issues:

- The custom identifier option seems non-functional
- CodeSpace value cannot be modified.

**Comment by alcinnz** [comment]
Shortterm actions: use MetadataLinkage to hold the resolvable URI UUID.

Make sure when harvested by Dublin Core & similar catalogues that this maps to ID.

**Comment by alcinnz** [comment]
Medium term: See if you can fix the custom UUID.

**Comment by alcinnz** [comment]
Long term: Resolve larger issues around UUID assignment & relationship to URL. Needs to be easy for the user.

**Comment by ByronCinNZ** [comment]
Issues:
- The custom identifier option seems non-functional
- CodeSpace value cannot be modified.

**Comment by alcinnz** [comment]
Moved to relevant fork.
