### ISSUE TITLE
MD_Constraints for metadata is not in the Metadata tab

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#39]
It's seperate to it.
This creates confusion because these constraints apply to the metadata and not the resource. Resource constraints are usually more important.

**Comment by ByronCinNZ** [comment]
This creates confusion because these constraints apply to the metadata and not the resource. Resource constraints are usually more important.

**Comment by alcinnz** [comment]
Out-of-scope for contract.
