### ISSUE TITLE
Button to populate creationDate with today's date

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#48]
Can do it just through the calendar as it shows todays date by default. All that is needed is to select it. Still a single click (a "now" button) would be better.

**Comment by ByronCinNZ** [comment]
Can do it just through the calendar as it shows todays date by default. All that is needed is to select it. Still a single click (a "now" button) would be better.

**Comment by alcinnz** [comment]
Moved to relevant fork.
