### ISSUE TITLE
CIParty (CIResponsibility)

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#52]
Capturing ORCIDs are both difficult & hard to see when you're done.
Simplify the process of capturing ORCIDs and viewing these.
Also may be in part a GN interface migration issue from 19139

**Comment by alcinnz** [comment]
Simplify the process of capturing ORCIDs and viewing these.

**Comment by ByronCinNZ** [comment]
#99 Also may be in part a GN interface migration issue from 19139

**Comment by alcinnz** [comment]
Out-of-scope for contract.
