### ISSUE TITLE
CI_Responsibility

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#53]
The difference adding a second CI_Responsibility element or a `party` under the same CI_Responsibility is not clear in the UI.

But CitedResponsibility allows adding of a role.
Need some additional guidance when to use which approach?

**Comment by ByronCinNZ** [comment]
Need some additional guidance when to use which approach?

**Comment by alcinnz** [comment]
Out-of-scope for contract.
