### ISSUE TITLE
CI_CitedResponsableParty

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#55]
Hangs after adding a cited responsable party from clicking "search for contact" button.
Can be worked around with a reload.
Populating the "managed directories" for "organizations & contacts" for both organization & name creates responsableParty for organization.

**Comment by alcinnz** [comment]
Can be worked around with a reload.

**Comment by alcinnz** [comment]
Populating the "managed directories" for "organizations & contacts" for both organization & name creates responsableParty for organization.

**Comment by ByronCinNZ** [comment]
#99

**Comment by alcinnz** [comment]
Moved to relevant fork.
