### ISSUE TITLE
Diminutive fonts for major elements e.g. Topic Category

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#60]
Text label font is too diminuitive.

NOTE: This may be true with all elements that do not have child elements.
Text for elements are too diminutive in the GN interface when they have no children. Makes them difficult to find. This could be enhanced.

**Comment by ByronCinNZ** [comment]
Text for elements are too diminutive in the GN interface when they have no children. Makes them difficult to find. This could be enhanced.

**Comment by alcinnz** [comment]
Moved to relevant fork.
