### ISSUE TITLE
Create a system to populate license information

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#64]
Source from a managed directory like "Organizations & contacts".
There seems to be a Search For Constraint option, but cannot figure out how to make it work. An autocompletion list flashes onscreen with a spinner, but never yields any results.

**Comment by alcinnz** [comment]
There seems to be a Search For Constraint option, but cannot figure out how to make it work. An autocompletion list flashes onscreen with a spinner, but never yields any results.

**Comment by ByronCinNZ** [comment]
#99

**Comment by alcinnz** [comment]
Moved to relevant fork.
