### ISSUE TITLE
Failed to search thesaurus

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#73]
The searchbox didn't bring up any results, and a sidebar for jumping around the form.

Other thasauri work, something seems to be wrong about how the UNESCO thesaurus was loaded...
Requires use of narrower/broader predicates?
We need better tools and instructions for determining valid thesauri!
When choosing keywords from a thasaurus there's no option to add a keyword class.
If the keyword class are attached to a thesaurus keyword it applies to all entries for that MD_Keywords element.

No workarounds possible via the XML view.
Partial workaround: Ensure all recommended thesauri are preloaded.

**Comment by alcinnz** [comment]
Requires use of narrower/broader predicates?

**Comment by alcinnz** [comment]
We need better tools and instructions for determining valid thesauri!

**Comment by alcinnz** [comment]
When choosing keywords from a thasaurus there's no option to add a keyword class.

**Comment by alcinnz** [comment]
If the keyword class are attached to a thesaurus keyword all entries for that MD_Keywords element.

No workarounds possible via the XML view.

**Comment by alcinnz** [comment]
Partial workaround: Ensure all recommended thesauri are preloaded.

**Comment by ByronCinNZ** [comment]
General Thesaurus issues

**Comment by ByronCinNZ** [comment]
#100

**Comment by alcinnz** [comment]
Out of scope for contract.
