### ISSUE TITLE
Resource Extent (Bounding Box)

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#74]
In keywords, the "compute extents from place keywords" button does not yield the expected result. It shows spinner temporarily as if it did something, but doesn't appear to change the metadata.
This fuctionality does work in the Extents-> bounding box interface

**Comment by ByronCinNZ** [comment]
This fuctionality does work in the Extents-> bounding box interface

**Comment by alcinnz** [comment]
Moved to relevant repo.
