### ISSUE TITLE
Tabs should stay at top of page

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#75]
They shouldn't dissappear when you scroll.
GN interface improvement. Tabs should also be reviewed for templates use so that less data appears on some tabs like "identification"

**Comment by ByronCinNZ** [comment]
GN interface improvement. Tabs should also be reviewed for templates use so that less data appears on some tabs like "identification"

**Comment by alcinnz** [comment]
Moved to relevant repo.
