### ISSUE TITLE
Labels to add sibling elements are often non-present

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#76]
There's plus buttons for sibling elements that unlabeled & unclear.
The GN edit interface can be somewhat confusing as to the nesting of elements and what buttn to click to create siblings. This could be made more clear.  It helps to set the display to “Colored indents” in “Admin Console” -> “Settings” -> “User interface” -> “Editor page indent types”.
![image](https://user-images.githubusercontent.com/1085756/94605573-cfb63500-02f5-11eb-86a0-9c32e3848951.png)

**Comment by ByronCinNZ** [comment]
The GN edit interface can be somewhat confusing as to the nesting of elements and what buttn to click to create siblings. This could be made more clear

**Comment by alcinnz** [comment]
Moved to relevant repo.
