### ISSUE TITLE
Reference System Information

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#78]
The identifier search control populates the code with the namespace (e.g. EPSG:) and together with the code (e.g. EPSG:4326). This is counter to current advice.

The code holds the code, & the namespace holds the namespace.
Need to come to common agreement on best way to show Reference system identifiers. This may be done in conjuction with data epoch changes in the latest revision of 19115-3. This revision also adds the ability to provide RS info in more detailed fashion
Manage Directory could be enhanced to support the standardised population of RS. But even better would be a link to Proj4 and import data from there into 19115-1 AMD 2(?) with Coord Epoch support

**Comment by ByronCinNZ** [comment]
Need to come to common agreement on best way to show Reference system identifiers. This may be done in conjuction with data epoch changes in the latest revision of 19115-3. This revision also adds the ability to provide RS info in more detailed fashion

**Comment by ByronCinNZ** [comment]
#99

**Comment by alcinnz** [comment]
Moved to relevant repo.
