### ISSUE TITLE
Distribution Information

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#79]
Recommend values for format names need review to include all the most common formats.
Note: Distribution information can be captured also in the "Associated Resources" panel under "Online Resources". guidance about which to use when may be helpful

**Comment by ByronCinNZ** [comment]
Note: Distribution information can be captured also in the "Associated Resources" panel under "Online Resources". guidance about which to use when may be helpful

**Comment by ByronCinNZ** [comment]
#99

**Comment by alcinnz** [comment]
Moved to relevant repo.
