### ISSUE TITLE
Display issue with Distributor

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#81]
When selecting a distributor from a Search For Contact, it leaves a misleading prompt under Distributor. Incorrectly marked mandatory, when the appropriate information is entered elsewhere.
This is inconsistent behaviour on GN

![](https://user-images.githubusercontent.com/1085756/94379370-4afbd780-018c-11eb-8e85-e81b21c39704.png)

**Comment by ByronCinNZ** [comment]
![image](https://user-images.githubusercontent.com/1085756/94379370-4afbd780-018c-11eb-8e85-e81b21c39704.png)

**Comment by ByronCinNZ** [comment]
This is inconsistent behaviour on GN

**Comment by alcinnz** [comment]
Moved to relevant fork.
