### ISSUE TITLE
Difficulty importing metadata of different versions of 19115-3

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#82]
Importing metadata of a different version of 19115-3 is difficult, due to changing namespaces.
old mdb namespace
xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/1.0

New mdb namespace -
xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0

We may need a import transform XSL

**Comment by alcinnz** [comment]
old mdb namespace
xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/1.0


New mdb namespace -
xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0

We may need a import transform XSL

**Comment by ByronCinNZ** [comment]
Hi all,
 
I have been looking at the getting GA’s ISO 19115-3 metadata validation tool to work with the version 2.0 namespaces, and of course nothing is ever straight forward.
 
The application is presently coded such that the schema locations do not need to be provided in the XML metadata document (i.e. xsi:schemaLocation attribute is not needed).  The schema location is configured in the application.  As a result, the application will not work with both version 1.0 namespace documents and version 2.0 namespace documents, i.e. I can make the application work with version 2.0 namespace documents although it will no longer work with version 1.0 namespace documents, and vice versa.
 
The application could be updated to dynamically check the document’s namespace declarations to see which namespace version it’s using and set the schema location accordingly, although this would require a fair bit of recoding.  A much simpler option in terms of recoding would be to modify the application to use schema locations provided in the XML metadata document.  This would obviously require documents submitted for validation to include the xsi:schemaLocation attribute containing the location of all XSDs required to validate the document.
 
I would be keen to get your thoughts on the importance of being able to validate documents that don’t include the schema locations.  In the case of the ISO 19115 metadata provided by GA, schema locations are always provided in the documents (which is really a reflection of the GeoNetwork software used to generate and manage the metadata), although are there other users who will want to submit documents without schema locations? 
 
Perhaps an item for discussion at the next MDWG meeting.
 
Thanks,
 
Aaron Sedgmen  |  Web Services Developer
Minerals, Energy and Groundwater Division  |  Information Services
 
t +61 2 6249 9576    www.ga.gov.au

**Comment by alcinnz** [comment]
Moved into relevant fork.
