### ISSUE TITLE
"Search For Contacts" coming up empty for MetadataContact

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#83]
Searching for contact for the `MD_Metadata > mdb:contact` "search for a contact" button fails.
![image](https://user-images.githubusercontent.com/1085756/94625581-8fff4580-0315-11eb-827c-ca6fd0233a27.png)

**Comment by ByronCinNZ** [comment]
#99

**Comment by alcinnz** [comment]
Moved to relevant fork.
