### ISSUE TITLE
Element MetadataSxope "name" is misleading (ISO19115 issue)

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#85]
MetadataScope has an element titled name which is to hold a "description of the scope".
This is a description field not a "name" field. Could rename in the interface.
Interface enhancement

**Comment by ByronCinNZ** [comment]
This is a description field not a "name" field. Could rename in the interface.
- Interface enhancement

**Comment by alcinnz** [comment]
Moved to relevant fork. Maybe?

**Comment by alcinnz** [comment]
Moved to relevant fork. Maybe?
