### ISSUE TITLE
Responsible Party in Manage Directory lacks ability to save identifiers for parties

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#87]
Identifiers like ORCIDs should travel with the stored contact information.
Workaround is to add it after importing stored information.
Related: Should contact information be populated in the template or encourage using the "Search for contact" option?
How do we best do this in the template?
![image](https://user-images.githubusercontent.com/1085756/94625415-30a13580-0315-11eb-9250-80ea0432328d.png)

**Comment by alcinnz** [comment]
Workaround is to add it after importing stored information.

**Comment by alcinnz** [comment]
Relatedly: Should contact information be populated in the template or encourage using the "Search for contact" option?

**Comment by ByronCinNZ** [comment]
#99

**Comment by alcinnz** [comment]
Moved to relevant fork.
