### ISSUE TITLE
"Citation" -> "Website" isn't the best label

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#89]
Linkage would better reflect the standard.
Throughout the GN interface, "website" is used in the "citation" package to indicate where a online linkage should be captured. As this is not always a website, the label would better be something like "Online Link"

**Comment by ByronCinNZ** [comment]
Throughout the GN interface, "website" is used to indicate where a online linkage should be captured. As this is not always a website, the label would better be something like "Online Link"

**Comment by alcinnz** [comment]
Moved to relevant fork.
