### ISSUE TITLE
Service Type

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#90]
Should not use the suggested dropdown items for Service Type. Rather should use a different vocabulary.

Enhancement: new options could be "discovery", "view", "download", "transformation", or "invoke".
This is a somewhat confusion issue. The standard lacks clarity about how this element and related elements (ServiceType, ServicewVersion, profile and ServiceStandard). More firm agreement and guidance from MDWG would be helpful as these are likely xearch parameters. Computers need to know how to find and index these values
![image](https://user-images.githubusercontent.com/1085756/94625317-f59f0200-0314-11eb-8632-3dce4bd37778.png)

**Comment by ByronCinNZ** [comment]
This is a somewhat confusion issue. The standard lacks clarity about how this element and related elements (ServiceType, ServicewVersion, profile and ServiceStandard). More firm agreement and guidance from MDWG would be helpful as these are likely xearch parameters. Computers need to know how to find and index these values

**Comment by ByronCinNZ** [comment]
#99

**Comment by alcinnz** [comment]
Moved to relevant fork.
