### ISSUE TITLE
Parameters checkboxes being required is confusing

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#92]
Usually this indicates that the checkbox is required to be ticked, as in the lie "I agree to the terms and conditions".

There is a checkbox for "optionality", and a checkbox for "repeatability".
These should be replaced with yes / no option as a user interface enhancement

**Comment by ByronCinNZ** [comment]
These should be replaced with yes / no option

**Comment by alcinnz** [comment]
Moved to relevant fork.
