### ISSUE TITLE
Coupled Resource

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#93]
The "Associated resources" box provides a way to link a resource to a dataset. This puts the link in the wrong spot.

It's in the sidebar section, but "Add linko a dataset" puts it in "operatesOn".
The associated resource tool in Geonetwork should provide a way to link a coupled dataset to the service. But it does not, at least not correctly.

"Link to a dataset", "Link to a source dataset" neither of these put anything in the metadata itself. Link to an online resource does, but it puts it in "operates on" rather than "coupled resource".

**Comment by alcinnz** [comment]
The associated resource tool in Geonetwork should provide a way to link a coupled dataset to the service. But it does not, at least not correctly.

"Link to a dataset", "Link to a source dataset" neither of these put anything in the metadata itself. Link to an online resource does, but it puts it in "operates on" rather than "coupled resource".

**Comment by alcinnz** [comment]
Removing the dataset from the associated resources does not necessarily remove it from the metadata.

**Comment by ByronCinNZ** [comment]
#94

**Comment by alcinnz** [comment]
Moved to relevant fork.
