### ISSUE TITLE
"Source dataset" puts a reference in lineage as "source"

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#94]
In GeoNetwork there is a frame titled "Associated   Resources" in the right-hand column by which one associates various   resources to the metadata record. For the most part, such associations can   also be captured in the main editor. This interface allows one to browse to   the resource to link. However, there are several issues with this   interface:      It is poorly named. "Associated Resources" would suggest   the entries land in the "mri:associatedResource" element     The options under "Add" do not adequately indicate which packages   and elements they populate.     It is difficult to modify where these linkages land when there is more than   one possible approach, e.g. coupledResource vs. operatedDataset vs.   operatesOn     Associated resources -> "Add" -> "Link to source   dataset" puts a reference in lineage as "source". While this   may be useful, this result is not indicated.     There is not a method to capture "Coupled Resource".      Source dataset puts a reference in lineage as “source”. While useful,   it is not apparent in the interface that this will be the result.

"Associated resources" -> "Add" -> "Link to source dataset" puts a reference in lineage as "source".
This is not a method to capture "Coupled Resource", should be more clear.
In GN there is a frame titled "Associated Resources" in right hand column in which various types of resources can be associated to the metadata record. For the most part, such associations can be also captured in the metadata itself. This interface allows one to browse to the resource to link. However, there are several issues with this interface:

It is badly named. "Associated Resources" would suggest the entries land in the "mri:associatedResource" element
The options under "Add" do not adequately indicate which packages and elements they populate.
It is difficulat to modifiy where these linkages land when there is more than one possible approach, e.g. coupledResource vs. operatedDataset vs. operatesOn

**Comment by ByronCinNZ** [comment]
In GN there is a frame titled "Associated Resource" in right hand column in which various types of resources can be associated to the metadata record. For the most part, such associations can be also captured in the metadata itself. This interface allows one to browse to the resource to link. However, there are several issues with this interface:

- It is badly named. "Associated Resources" would suggest the entries land in the "mri:associatedResource" element
- The options under "Add" do not adequately indicate which packages and elements they populate.
- It is difficulat to modifiy where these linkages land when there is more than one possible approach, e.g. coupledResource vs. operatedDataset vs. operatesOn

**Comment by alcinnz** [comment]
Moved to relevant fork.
