### ISSUE TITLE
Cannot create thesaurus using INSPIRE registries

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#97]
Works in latest version, GeoNetwork 4.0
"The Classification of Spatial Data Services" was able to be uploaded, but unable to set the thesaurus type to "service" in the interface.
This is about using the internal INSPIRE thesaurus loading in GeoNetwork. using the button in the Admin/Classification interface
![image](https://user-images.githubusercontent.com/1085756/94624664-752bd180-0313-11eb-8fd9-a084450679f8.png)

**Comment by alcinnz** [comment]
Works in latest version, GeoNetwork 4.0

**Comment by alcinnz** [comment]
"The Classification of Spatial Data Services" was able to be uploaded, but unable to set the thesaurus type to "service" in the interface.

**Comment by ByronCinNZ** [comment]
This is about using the internal INSPIRE thesaurus loading in GeoNetwork. using the button in the Admin/Classification interface

**Comment by ByronCinNZ** [comment]
#100

**Comment by alcinnz** [comment]
Moved to relevant fork.
