### ISSUE TITLE
Manage Directory/OnlineResources issue

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/mdwg#98]
Manage Directories contains an online Resources type that seems to be for capturing distributionInfo. But there is no link from the GeoNetwork interface for ISO19115-3 records to insert these metadata fragments about distribution.

The format for this distributionInfo is ISO19139.

**Comment by ByronCinNZ** [comment]
#99

**Comment by ByronCinNZ** [comment]
#99

**Comment by alcinnz** [comment]
Out of scope for this contract.
