### ISSUE TITLE
Managed directory

### ISSUE THREAD

**Issue by ByronCinNZ** [OpenWork-NZ/mdwg#99]
The "Manage directory" interface on the editor board is a great place to store contacts. But it could be used for much more e.g. Constraint info. distribution formats, standards. It currently holds a non functional distribution info section that is not referenced by the metadata (Whether it would be useful is unclear as the cdownload link would have to change for each entry.) 
Many issues are related to this:
- Lack of support or documentation for additional packages e.g. constraints, formats, standards
- Location of tool logically should be alongside thesaurus
- May be issues of alignment with 19139 rather than 19115-3
![image](https://user-images.githubusercontent.com/1085756/94625063-5da11880-0314-11eb-9601-74958b247464.png)
![image](https://user-images.githubusercontent.com/1085756/94625139-8a553000-0314-11eb-8a48-fe7c33691f05.png)

**Comment by alcinnz** [comment]
Moved to relevant fork.
